name: smart_cage
description: SmartCage — ChirpGuard Poultry Farm Monitoring App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0
  intl: ^0.20.2
  http: ^1.2.2
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app icon/icon.jpg"

flutter:
  uses-material-design: true

dependency_overrides:
  path_provider_foundation: 2.3.2
